### ISSUE TITLE
Update 1.0.1

### ISSUE THREAD

**Issue by iwex** [jenssegers/laravel-rollbar#83] opened 2017-05-11 12:46 UTC
Hello! Please Update Rollbar library https://github.com/rollbar/rollbar-php/releases/tag/v1.0.1

**Comment by ChadTaljaardt** [comment] 2017-05-13 13:02
This is a duplicate of https://github.com/jenssegers/laravel-rollbar/issues/81

**Closed** 2017-05-13 13:27 UTC
